# Generated by Django 3.1.1 on 2020-10-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_product_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(default=True, max_length=32),
        ),
    ]
