# Generated by Django 3.1.1 on 2020-10-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201004_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crator',
            field=models.CharField(default='Webmaster', max_length=32),
        ),
    ]
