# Generated by Django 3.1.1 on 2020-10-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201006_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(default='unavailable.jpg', max_length=256, null=True),
        ),
    ]
