# Generated by Django 3.1.1 on 2020-10-11 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comments',
            name='onproduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.product'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.product'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 1, 7, 25, 809979)),
        ),
    ]
