# Generated by Django 3.1.1 on 2020-10-13 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201013_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 1, 0, 20, 692727)),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='auctions.product'),
        ),
    ]
